# Generated by Django 4.1.4 on 2023-06-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_rename_name_user_firstname_user_lastname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Lastname",
            field=models.CharField(max_length=200),
        ),
    ]
