# Generated by Django 4.1.4 on 2023-06-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_alter_user_lastname"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="viici",
        ),
    ]
