# Generated by Django 4.1.4 on 2023-06-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="User",
        ),
    ]
