# Generated by Django 4.1.4 on 2023-06-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_alter_user_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
    ]
