# Generated by Django 4.1.4 on 2023-07-06 18:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_remove_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_desc", models.CharField(max_length=400)),
                ("post_title", models.CharField(max_length=150)),
                ("post_content", models.TextField()),
                (
                    "post_user_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "post_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("post_created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
