# Generated by Django 4.1.4 on 2023-07-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_post"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table="post",
        ),
    ]
