# Generated by Django 4.1.4 on 2023-07-15 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_alter_post_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
